### ISSUE TITLE
Same problem as "bocik1 " Cant run the game

### ISSUE THREAD

**Issue by wastermann** [Alteruna/Multiplayer-FPS-Template#4] opened 2023-09-13 09:01 UTC
Hi!
The Multiplayer scene in play-mode get this errors (Unity version 2022.3.1F1):

Assets\AlterunaFPS\Scripts\CinemachineVirtualCameraInstance.cs(12,10): error CS0246: The type or namespace name 'CinemachineVirtualCamera' could not be found (are you missing a using directive or an assembly reference?)

[Worker0] Internal: There are remaining Allocations on the JobTempAlloc. This is a leak, and will impact performance

[Worker0] To Debug, run app with -diag-job-temp-memory-leak-validation cmd line argument. This will output the callstacks of the leaked allocations.

[Worker0] Internal: There are remaining Allocations on the JobTempAlloc. This is a leak, and will impact performance

[Worker0] To Debug, run app with -diag-job-temp-memory-leak-validation cmd line argument. This will output the callstacks of the leaked allocations.

[Worker0] Internal: There are remaining Allocations on the JobTempAlloc. This is a leak, and will impact performance

[Worker0] To Debug, run app with -diag-job-temp-memory-leak-validation cmd line argument. This will output the callstacks of the leaked allocations.

[Worker0] Internal: There are remaining Allocations on the JobTempAlloc. This is a leak, and will impact performance

[Worker0] To Debug, run app with -diag-job-temp-memory-leak-validation cmd line argument. This will output the callstacks of the leaked allocations.

**Comment by wastermann** [comment] 2023-09-13 09:04
Running Unity version 2023.3.1F1

**Comment by SimonAlteruna** [comment] 2023-09-28 12:24
Duplicate of #3
You need the Cinemachine package installed. Please install it from the package manager.

**Closed as completed by SimonAlteruna** 2023-09-28 12:24 UTC
Labels: duplicate
